name: Deploy

on:
  push:
    tags: [ "*" ]

env:
  IMAGE_NAME: twitter-watcher
  DEPLOYMENT_WEBHOOK: ${{ secrets.DEPLOYMENT_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: type=ref,event=tag
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: TwitterWatcher/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Hit deployment webhook
      run: |
        curl --request POST --url "$DEPLOYMENT_WEBHOOK"
